name: uri_parser
description: A minimal & safe utility to parse URIs.
homepage: https://github.com/alexmercerind/uri_parser
repository: https://github.com/alexmercerind/uri_parser
version: 3.0.2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
